### ISSUE TITLE
How to generate list

### ISSUE THREAD

**Issue by redxtech** [groovykiwi/rofi-nerdfont#1]
Hey, I'm wondering if you would be able to share how you generated the list of icons, I was hoping I could do the same, making sure it has all icons and is up-to-date and everything.

**Comment by nathanhoulamy** [comment]
Hi, it has been a while since I've done this but from my memory I copied the source code from the official [cheat sheet](https://www.nerdfonts.com/cheat-sheet) and used the `sed` command on my Linux system to trim all the unwanted text leaving me with just the class name and hex code of the icons. If I remember correctly to display icons using the hex code you need to just escape it with a backslash like so `\e711`.

**Comment by redxtech** [comment]
Yeah, that sounds pretty much like what I ended up doing. I downloaded the source for the cheat sheet page, and then running a script on it. The script is just chained `tr`, `sed`, `awk`, `grep`, and `xargs` commands.

https://github.com/redxtech/dotfiles/blob/master/.local/bin/gen-nerd-icons

**Comment by nathanhoulamy** [comment]
I'm glad you managed to generate the list. Thanks for linking your script it can come in handy later on.
